BOWER_COMPONENTS =
	'angular': '1.3.8':
		scripts: 'angular.min.js'
	'angular-animate': '1.3.8':
		scripts: 'angular-animate.min.js'
	'angular-mocks': '1.3.8':
		scripts: 'angular-mocks.js'
	'angular-loading-bar': '0.6.0':
		scripts: 'build/loading-bar.min.js'
		styles:  'build/loading-bar.min.css'
	'angular-loading-bar': '0.6.0':
		scripts: 'build/loading-bar.min.js'
		styles:  'build/loading-bar.min.css'
	'angular-ui-router': '0.2.10':
		scripts: 'release/angular-ui-router.min.js'
	'bootstrap': '3.3.1':
		fonts:   'dist/fonts/**/*.{eot,svg,ttf,woff}'
		styles:  'dist/css/*.min.css'
	'google-code-prettify': '1.0.3':
		scripts: 'src/prettify.js'
		styles:  'src/prettify.css'
	'Faker': '3.0.0':
		scripts: 'build/build/faker.min.js'
	'mustache': '2.1.2':
		scripts: 'mustache.min.js'
	'showdown': '0.3.1':
		scripts: 'src/showdown.js'

module.exports = {BOWER_COMPONENTS}
